### ISSUE TITLE
LAN access

### ISSUE THREAD

**Issue by alexchern** [livekit-examples/meet#122]
Hi,

I can build and run the demo on localhost, but when attempting to access the demo site on a LAN, I encounter the following error:

```
Unhandled Runtime Error
Error: Accessing media devices is available only in secure contexts (HTTPS and localhost), in some or all supporting browsers. 
```
I have set the URL in the .env.local file as follows:

```
# URL pointing to the LiveKit server.
LIVEKIT_URL=ws://192.168.1.42:7880
```

Could you please advise on how I can access the server on the LAN (without https)? I attempted to use a reverse proxy (nginx), but I may have made an error in the setup.

Thank you for your assistance.

Best regards,

Alex

**Comment by davidzhao** [comment]
This is part of browser security policy, unfortunately we cannot do anything about that.

You can look into using something like ngrok, where they could terminate SSL for you.
