### ISSUE TITLE
No video in Safari iOS 17

### ISSUE THREAD

**Issue by ottob** [livekit-examples/meet#145]
We use a URL like this:
https://meet.livekit.io/custom?liveKitUrl=wss://our-server.livekit.cloud&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tSm9pbiI6dHJ1ZSwicm9vbSI6ImkyN1lQaDFKVmVKWTZpRnA4Nzc2In0sIm5hbWUiOiJPdHRvIEJyZXR6IiwiaWF0IjoxNjk4MzEwMzU2LCJuYmYiOjE2OTgzMTAzNTYsImV4cCI6MTY5ODMzMTk1NiwiaXNzIjoiQVBJWjlFOHBoamVOOGtDIiwic3ViIjoiOUg2N2xJSU1zdFRIVDlNTzdkNksiLCJqdGkiOiI5SDY3bElJTXN0VEhUOU1PN2Q2SyJ9.npq9KylORSXkVu8oVK1NWb-5M1iaz2Uq-KmAkJZA1tU#dmVyeXNlY3JldA==

Recently the video has stopped working.
![IMG_0185](https://github.com/livekit-examples/meet/assets/67104/023c26e1-d7be-4d9a-ae21-97ebad425e66)

We get this message in the develop console.
> Unhandled Promise Rejection: Error: cannot publish track, codec not supported by server

Also worth noting a possible regression. In the meet ui now the footer blocks the connect button on the custom tab, and it is not possible to scroll to make it visible:
![IMG_0184](https://github.com/livekit-examples/meet/assets/67104/d64f4e5b-6a3b-4fc7-b2ce-dfe14ddd3041)

**Comment by ottob** [comment]
Maybe this broke with the recent vp9 changes?
If I revert to a2e04f7048b8e2b6150dbdf7857930f9fc9d1d38 it starts working again.

I found out that VP9 was not enabled in my settings here:
https://cloud.livekit.io/projects/OUR ID/settings/project

But enabling VP9 there made no difference.

**Comment by lukasIO** [comment]
hi @ottob, yeah, this is likely related to vp9 being set as default for the custom connection tab. 
It's odd that enabling VP9 in your config doesn't make a difference.
Can you try again after a couple of minutes?

**Comment by ottob** [comment]
I tried again now, and it seems like the VP9 setting in the admin page did work now. Thanks!
