### ISSUE TITLE
Using demo on localhost works fine, but using demo on the server to display Disconnected

### ISSUE THREAD

**Issue by yyl1988** [livekit-examples/meet#170]
No error when using demo in localhost. However, when the demo is deployed to the server, the state of the Room object generated by the new Room isconnected, but the interface is always displayed Disconnected, never in a connecting state, and it is Disconnected from beginning to end

![livekit cannot connect](https://github.com/livekit-examples/meet/assets/44868226/741248c7-5a6b-4b70-9450-6538cf9cad82)

**Comment by yyl1988** [comment]
![Uploading livekit cannot connect.jpg…]()

**Comment by davidzhao** [comment]
You need to configure your server correct. see [docs](https://docs.livekit.io/realtime/self-hosting/deployment/) and [connection-tester](https://livekit.io/connection-test)

**Comment by yyl1988** [comment]
> 您需要正确配置服务器。参见 [docs](https://docs.livekit.io/realtime/self-hosting/deployment/) 和 [connection-tester](https://livekit.io/connection-test)
![image](https://github.com/livekit-examples/meet/assets/44868226/cad0ff4e-a748-46d7-a7ad-07d3f8e9e135)

Through the connection-tester test, livekit services can be connected normally, proving that the server configuration is correct

**Comment by yyl1988** [comment]
> 您需要正确配置服务器。参见 [docs](https://docs.livekit.io/realtime/self-hosting/deployment/) 和 [connection-tester](https://livekit.io/connection-test)
After the demo is packaged and run on the tomcat environment of the localhost, it is found that localhost:3000, and the interface is displayed as Disconnected
