### ISSUE TITLE
Using demo on localhost works fine, but using demo on the server to display Disconnected

### ISSUE THREAD

**Issue by yyl1988** [livekit-examples/meet#171]
Through the connection-tester test, livekit services can be connected normally, proving that the server configuration is correct

![Uploading image.png…]()

After the demo is packaged and run on the tomcat environment of the localhost, it is found that localhost:3000, and the interface is displayed as Disconnected

**Comment by yyl1988** [comment]
<img width="960" alt="Snipaste_2023-12-05_15-14-04" src="https://github.com/livekit-examples/meet/assets/44868226/4ced50ba-c725-44b1-83e7-51e602d19a2e">

**Comment by lukasIO** [comment]
> Through the connection-tester test, livekit services can be connected normally,

No, please read the warnings in the connection tester output. It says `Your server is likely not configured correctly`.
