### ISSUE TITLE
how to modify http to https , in public web, the WSS need https

### ISSUE THREAD

**Issue by steamed-bun-with-brown-sugar** [livekit-examples/meet#178]
I'm sorry to put this simple issue, but i'm really got no way to figure it, the WSS need https to keep security, after I pull the code and successfully run it  with the livekit server i' build by myself.  I find out when i run the client on the node.js with nginx proxy a https port to original http,  the wss couldn't make a connection to meet client port, thus  the remotely vedio could not show content . In the client code ,I can not find place to correct the http to https. 
I am very grateful for your help in solving this problem. thank you very much !

**Comment by davidzhao** [comment]
Browsers require the use of HTTPS before it'll allow you to capture video from media devices. This is not our requirement.
