### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by lgz5689** [livekit-examples/meet#238]
What's happening?

node -v
v20.11.0
npm -v
10.2.4
pnpm -v
8.14.1

MacOS
brew install livekit-server
livekit-server --dev

.env.local
LIVEKIT_URL=ws://127.0.0.1:7880

pnpm i
pnpm run dev

```
Unhandled Runtime Error
Error: Authentication Error. Code 25683

Call Stack
yI.rE
node_modules/.pnpm/@livekit+krisp-noise-filter@0.2.1_livekit-client@2.0.10/node_modules/@livekit/krisp-noise-filter/dist/index.js (16609:0)
yI.setEnabled
node_modules/.pnpm/@livekit+krisp-noise-filter@0.2.1_livekit-client@2.0.10/node_modules/@livekit/krisp-noise-filter/dist/index.js (16586:0)
o.B
node_modules/.pnpm/@livekit+krisp-noise-filter@0.2.1_livekit-client@2.0.10/node_modules/@livekit/krisp-noise-filter/dist/index.js (16569:0)
o._onWasmWorkerMessage
node_modules/.pnpm/@livekit+krisp-noise-filter@0.2.1_livekit-client@2.0.10/node_modules/@livekit/krisp-noise-filter/dist/index.js (15970:0)
```

**Comment by lgz5689** [comment]
only can use npm run start？

**Comment by lukasIO** [comment]
are you setting `NEXT_PUBLIC_SHOW_SETTINGS_MENU` in any env file? 

when exactly does that error occur? 
directly after running `pnpm run dev` or after opening the browser and joining a room?

**Comment by lgz5689** [comment]
.env
NEXT_PUBLIC_SHOW_SETTINGS_MENU=true

running pnpm run dev or after opening the browser no error

joining a room will show this error

**Comment by lukasIO** [comment]
yeah, so currently the settings menu is only supported for livekit cloud projects as it enables the krisp audio integration. 
To fix this for now, just set NEXT_PUBLIC_SHOW_SETTINGS_MENU=false

**Comment by lgz5689** [comment]
> yeah, so currently the settings menu is only supported for livekit cloud projects as it enables the krisp audio integration. To fix this for now, just set NEXT_PUBLIC_SHOW_SETTINGS_MENU=false

It is recommended to add this description to the.env.example file

**Comment by lukasIO** [comment]
addressed in https://github.com/livekit-examples/meet/commit/51a47a02d8ef1e6cb935bbf6f5cdf72ecc218230
