### ISSUE TITLE
Leave button error

### ISSUE THREAD

**Issue by BukhryakovVladimir** [livekit-examples/meet#263]
When pressing leave button in custom room an error occurs, and onLeave function doesn't execute, so there is no redirect with router.push.
![image](https://github.com/livekit-examples/meet/assets/43881945/1b600ba9-d976-44f8-a02b-345a2e122916)

How to reproduce:
start livekit-server in dev mode
create token and enter custom room on livekit.meet.io (or on localhost)
press Leave button

**Comment by lukasIO** [comment]
This error should not prevent any further code execution. 
Are you sure that this exact error is responsible for `router.push` not working?
