### ISSUE TITLE
I am trying to publish the Meet project as an H5 website, but I have encountered some issues

### ISSUE THREAD

**Issue by 0915416855** [livekit-examples/meet#322]
In Android 14 devices, the browser can retrieve the number of cameras and audio devices, but cannot display labels. In Android webview, it is not possible to obtain the camera and audio device. I have checked the web API and it supports Android webview, so I need you to check if it is a bug

**Comment by lukasIO** [comment]
webview's have some limitations so we don't officially support them. 
As a note the app opening the webview needs the appropriate permissions set. 
see https://stackoverflow.com/questions/71020526/does-navigator-mediadevices-getusermedia-work-on-hybrid-apps
