### ISSUE TITLE
bug: e2ee not work when first enter room

### ISSUE THREAD

**Issue by showonne** [livekit-examples/meet#358]
I'm using Custom Server demo to test base functionality. After enter server url, token and Passphrase to connect server, I can enter room successfully, but the e2ee is not worked as expected, My profile does not appear the lock icon and the data not decoded correctly, but after refresh the page, the lock icon appeared and the data decoded correctly.

**Comment by lukasIO** [comment]
is this on the `custom` connection? 
could you post the logs?

**Comment by showonne** [comment]
yes, it is on the `custom` connection. When I first enter room, there is no logs related to e2ee, and after reload pafe by cmd + R, logs contain `setting up e2ee` and the e2ee is successed. what logs do I need to provide ? I found an error in console, not sure if it's relevat to this issue.
![image](https://github.com/user-attachments/assets/cb7a5518-3c5a-4957-b3df-30cde57a6820)
![image](https://github.com/user-attachments/assets/e1b20ed4-c213-4540-a506-697f79041045)
