### ISSUE TITLE
Android/Chrome camera popup empy

### ISSUE THREAD

**Issue by ile** [livekit-examples/meet#96]
Using Meet with Chrome on Android, the camera popup has no texts. Clicking the options in it still works (can switch to rear camera and back to front).

![IMG_5178](https://github.com/livekit-examples/meet/assets/433707/8fc6eef0-894e-476a-a461-fd8db9a96624)

**Comment by Ocupe** [comment]
Hi @ile, thanks for the report. 👍 
Can you share what phone, OS version, and Chrome version you used? I don't have an Android phone at hand, so I could only test it with BrowserStack (where it worked for me).

**Comment by ile** [comment]
Yes sure, sorry I didn't include those already.

Samsung Galaxy A03, Android 13, and "One UI Core version 5.1".

I had to get an actual Android phone for app testing, as I noticed I will see more issues that way.

**Comment by lukasIO** [comment]
Did you allow all permissions? 
Are you seeing this on `https://meet.livekit.io` too or only on a locally hosted example?

I tried to repro on meet.livekit.io with a Samsung Galaxy S10+ Android 12 and could not reproduce

**Comment by ile** [comment]
I couldn't reproduce it on https://meet.livekit.io. I will test on another server soon to see if it's server related.

**Comment by ile** [comment]
Texts work fine on the other server. Sorry about the false alarm. :face_with_head_bandage:
